on: [push]
name: Static Analysis

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build Composer
        uses: php-actions/composer@v5
      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          installComposer: 0
          phpstanVersion: ^0.12
          level: 8
          paths: src 
          arguments: --autoload-file vendor/autoload.php

